spring:
  datasource:
    url: jdbc:mysql://localhost:3306/djlogistics?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.csdj.pojo
  config-location: classpath:mybatis/mybatis-config.xml

